site:
  title: Baltimore NodeSchool
  links:
    github: https://github.com/nodeschool/baltimore
    twitter: http://twitter.com/charmcityjs
  events:
    -
      start: 2017-08-19T13:00:00-04:00
      end: 2017-08-19T17:00:00-04:00
      registerLink: https://ti.to/baltimorenodeschool/twelve
      location:
        name: Betamore City Garage
        link: http://www.citygarage.vc/
      workshops: ["Prototypes", "Learn You Node", "Javascripting", "Advanced Topics"]
      sponsors:
        - charmCityJS
        - Betamore

    -
      start: 2017-11-12T13:00:00-05:00
      end: 2017-11-12T17:00:00-05:00
      location:
        name: Betamore City Garage
        link: https://betamore.com

workshops:
  -
    name: Prototypes
    description: Our August special focus is going to be object prototypes. Deepen your understanding of JavaScript objects by learning about prototypes, the prototype chain, and constructor calls of functions.
    link: https://github.com/yosuke-furukawa/tower-of-babel

  -
    name: Learn You Node
    description: An introduction into NodeJS and all the really cool things you can do with JavaScript outside of the browser! A basic understanding of JavaScript is recommended.
    link: https://github.com/workshopper/learnyounode

  -
    name: Javascripting
    description: A great place to start if you don't know any JavaScript and want to learn this amazing language.
    link: https://github.com/sethvincent/javascripting

  -
    name: Advanced Topics
    description: Explore any of the other adanced NodeSchool topics like Stream-Adventures, WebGL, Web Audio, Browserify, etc. If there's a NodeSchool lesson, we will help you with it.
    link: http://nodeschool.io/#workshoppers

sponsors:
  -
    name: charmCityJS
    link: http://charmcityjs.com
  -
    name: Betamore
    link: https://betamore.com
