site:
  title: Baltimore NodeSchool
  links:
    github: https://github.com/nodeschool/baltimore
    twitter: http://twitter.com/baltimorenodeschool
  events:
    -
      start: 2015-12-05T13:00:00-05:00
      end: 2015-12-05T17:00:00-05:00
      registerLink: https://ti.to/baltimorenodeschool/five
      location:
        name: Betamore
        link: https://betamore.com
      workshops: ["Learn You Node", "Javascripting", "Stream Adventure", "Browserify Adventure"]
      sponsors: ["charmCityJS", "Betamore"]
    -
      start: 2015-03-29T13:00:00-05:00
      end: 2015-03-29T17:00:00-05:00
      registerLink: https://ti.to/baltimorenodeschool/four
      location:
        name: Digital Harbor Foundation

workshops:
  -
    name: Learn You Node
    description: for learning node
    link: https://github.com/workshopper/learnyounode
  -
    name: Javascripting
    description: for those interested in learning JavaScript itself
    link: https://github.com/sethvincent/javascripting
  -
    name: Stream Adventure
    description: for a more advanced lesson
    link: https://github.com/substack/stream-adventure
  -
    name: Browserify Adventure
    description: if you want to experiment with npm + browsers
    link: https://github.com/substack/browserify-adventure

sponsors:
  -
    name: charmCityJS
    link: http://charmcityjs.com
  -
    name: Betamore
    link: https://betamore.com
